nacos:
  config:
    server-addr: 127.0.0.1:8848

logging:
  #自定义路径(必须要配置的日志路径)
  file:
    name: D:\LOGS\demoqy.log

spring:
  datasource:
    #    type: com.zaxxer.hikari.HikariDataSource
    #    url:  jdbc:sqlserver://localhost:1433;database=qiuyu
    #    username: sa
    #    password: 123456
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 50000
    jedis:
      pool.:
        max-active: 100
        max-idle: 50
        max-wait: 1500

server:
  port: 8080