spring:
  application:
    name: demo
  profiles:
    active: dev
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .html
    settings:
      classic_compatible: true
  jpa:
    open-in-view: false

logging:
  #根据不同的日志系统，你可以按如下规则组织配置文件名，就能被正确加载：
  #Logback：logback-spring.xml, logback-spring.groovy, logback.xml, logback.groovy
  #Spring Boot官方推荐优先使用带有-spring的文件名作为你的日志配置
  #默认的命名规则，并且放在 src/main/resources 下面即可；
  #logging.config属性指定自定义的名字。
  #config: classpath:logback-spring.xml
  level:
    ROOT: DEBUG
    io.github.jhipster: DEBUG
    com.qiuyu: DEBUG
  #自定义路径(必须要配置的日志路径)